# Generated by Django 3.1.4 on 2021-01-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='isim', db_index=True, default='standarturun', help_text='ürün ismi acklayici metin', max_length=100, null=True, unique=True, verbose_name='urunismi')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('stock_count', models.PositiveSmallIntegerField(verbose_name='stokadet')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ürünfiyat')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'urunler',
            },
        ),
    ]
